#!/bin/bash -el

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

echo "Deploying the Drupal application..."

APP_DIR=/home/application/current
SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy

# Deploying
echo "Starting application configuration"
[ -f /tmp/app_envs ] && source /tmp/app_envs
sudo -E ${VENV_DIR}/bin/python ${SOURCE_DIR}/drupal/deploy.py install
${VENV_DIR}/bin/python ${SOURCE_DIR}/drupal/deploy.py environment
