#!/bin/bash -el

echo "Deploying the Drupal application..."

SOURCE_DIR=/var/lib/tsuru
APP_DIR=/home/application/current
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/base/rc/config

APP_VENV=/home/application/.app_env

# Deploying
echo "Starting application configuration"
[ -f /tmp/app_envs ] && source /tmp/app_envs
sudo -E python ${SOURCE_DIR}/drupal/deploy.py install
python ${SOURCE_DIR}/drupal/deploy.py environment
