#!/bin/bash -el

apt-get -y update
apt-get -y install php5.6 php5.6-mcrypt php5.6-gd php5.6-mbstring php5.6-curl php5.6-cli php5.6-mysql php5.6-gd php5.6-intl php5.6-xsl php5.6-xml php5.6-zip --force-yes
apt-get install git -y --force-yes
apt-get install python python-yaml -y --force-yes
apt-get install wget -y --force-yes
apt-get install mysql-client -y --force-yes
apt-get install zip -y --force-yes
apt-get install unzip -y --force-yes
