#!/bin/bash -el

apt-get update
apt-get install git -y --force-yes
apt-get install python python-yaml -y --force-yes
apt-get install wget -y --force-yes
apt-get install mysql-client -y --force-yes
apt-get install php5-gd -y --force-yes
apt-get install php5-curl -y --force-yes
apt-get install libssh2-php -y --force-yes
apt-get install php5-mysql -y --force-yes
apt-get install zip -y --force-yes
apt-get install unzip -y --force-yes
apt-get install php5.5-xml -y --force-yes
